/*
 * A generator of unique bigint identifiers.
 *
 * Igor Konnov, 2023
 *
 * Copyright (c) Informal Systems 2021. All rights reserved.
 * Licensed under the Apache 2.0.
 * See License.txt in the project root for license information.
 */

/**
 * A generator of unique ids. Every such generator should guarantee that
 * it produces identifiers in a strict monotonically growing order.
 * It's fine to have gaps in the sequences of produced identifiers.
 */
export interface IdGenerator {
  /**
   * Generate the next identifier, which is different from the identifiers
   * that have been generated by this instance so far.
   */
  nextId(): bigint
}

/**
 * Introduce a new id generator.
 */
export const newIdGenerator = (initialId: bigint = 0n) => {
  return {
    _lastId: initialId,

    nextId(): bigint {
      this._lastId = this._lastId + 1n
      return this._lastId
    },
  }
}

/**
 * An id generator that always returns 0n, instead of a unique id.
 */
export const zerog = {
  nextId: (): bigint => 0n,
}
