/*
 * A generator of unique bigint identifiers.
 *
 * Igor Konnov, 2023
 *
 * Copyright 2021 Informal Systems
 * Licensed under the Apache License, Version 2.0.
 * See LICENSE in the project root for license information.
 */

/**
 * A generator of unique ids.
 */
export interface IdGenerator {
  /**
   * Generate the next identifier, which is different from the identifiers
   * that have been generated by this instance so far.
   */
  nextId(): bigint
}

/**
 * Introduce a new id generator.
 */
export const newIdGenerator = (initialId: bigint = 0n) => {
  return {
    _lastId: initialId,

    nextId(): bigint {
      this._lastId = this._lastId + 1n
      return this._lastId
    },
  }
}

/**
 * An id generator that always returns 0n, instead of a unique id.
 */
export const zerog = {
  nextId: (): bigint => 0n,
}
