[package]
name = "quint-connect"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
itf = "0.4.0"
quint-connect-macros = { path = "../connect-macros" }
serde = "1.0.228"
serde_json = "1.0.145"
tempdir = "0.3.7"
