[build]
  command = "npm install && next build"

[[redirects]]
  from = "/choreo"
  to = "https://quint.sh/docs/choreo"
  status = 301
  force = true

[[redirects]]
  from = "/choreo/*"
  to = "https://quint.sh/docs/choreo/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/docs/faq"
  to = "https://quint.sh/faq"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "https://quint.sh/:splat"
  status = 301
  force = true
